<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TestNameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('department_tests')->insert([
            ['name' => 'ANTI D ANTIBODY','department_id' => "1",'created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI D ANTIBODY TITRE','department_id' => "1",'created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BLOOD CROSS MATCH','department_id' => "1",'created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'COOMBS DIRECT','department_id' => "1",'created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'DIRECT COOMBS TEST','department_id' => "1",'created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR ANALYSIS', 'department_id' => "2",'created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID TAPPING', 'department_id' => "2",'created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BODY FLUID ANALYSIS', 'department_id' => "2",'created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERICARDIAL FLUID ANALYSIS', 'department_id' => "2",'created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID ANALYSIS', 'department_id' => "2",'created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR ANALYSIS', 'department_id' => "2",'created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '1 HOUR POST DINNER', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '1 HOUR POST LUNCH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS CREATININE CLEARANCE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS URINARY ALBUMIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS URINARY CALCIUM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS URINARY CITRATE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS URINARY NA, K', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS URINARY OSMOLARITY', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS URINARY OXALATES', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS URINARY URIC ACID', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS URINARY VMA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS URINE PROTEIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS VMA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'A/G RATIO (ONLY)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ACETYLCHOLINE RECEPTOR (ACHR) BINDING ANTIBODY', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ACETYLCHOLINE RECEPTOR (ACHR) BLOCKING ANTIBODY', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ACID PHOSPHATASE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ACTH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ADA (SPOT)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ALBUMIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ALKALINE PHOSPHATASE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ALPHA FETO PROTEIN -AFP- ELISA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'AMH (ANTI MULLERIAN HORMONE)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'AMYLASE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANA / ANF', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANA / IFA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANA / QUALITATIVE TEST', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANA PROFILE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI CARDIOLIPIN IGG', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI CARDIOLIPIN IGM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI CCP ANTIBODY', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI DS DNA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI GBM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI PHOSPH LIPID ANTIBODY ( IGG / IGM)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI THYROGLOBULIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI THYROGLOBULIN ANTIBODIES', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI TPO ANTIBODY', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI TRANSGLUTAMINE IGA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI TRANSGLUTAMINE IGG', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI TTG / IGG', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI TTG IGA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR ADA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR ALBUMIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR AMYLASE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR LDH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR PROTEIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR SUGAR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASO (QUANTITATIVE)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASO TITRE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'B-HCG QUANTITATIVE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BILIRIBIN D/T', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BODY FLUID ADA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BODY FLUID ALBUMIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BODY FLUID AMYLASE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BODY FLUID LDH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BODY FLUID PROTEIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BODY FLUID SUGAR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BUN(BLOOD UREA NITROGEN)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'C-ANCA P-ANCA ANTI GBM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'C-PEPTIDE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'C3 / C4', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CA 125 (ELISA)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CA 15.3 (ELISA)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CA 19.9 (ELISA)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CALCIUM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CALCIUM CREATININE RATIO', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CD 4 / CD 8 CELL COUNT', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CD 4 CELL COUNT', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CEA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CERULOPLASMIN LEVEL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CHOLESTEROL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CORTISOL (SERUM)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CPK', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CPK-MB', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CREATININE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CREATININE CLEARANCE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CRP (QUANTITATIVE)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CRP QUALITATIVE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CRP TITER', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CSF ALBUMIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CSF FOR ADA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CSF FOR LDH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CSF PROTEIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CSF SUGAR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'D-DIMER', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ENA PARAMETERS IMMUNOASSAY', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ENA PROFILE QUALITATIVE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ENA PROFILE QUANTITATIVE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ESTRADIOL / ESTROGEN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FASTING INSULIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FDP', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FERRITIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR ADA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR ALBUMIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR LDH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR PROTIEN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR SUGAR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR URIC ACID', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FOLIC ACID', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FSH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'G6PD', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GAMMA GT', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GBM IMMUNOBOLT', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLOBULIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLOMERULAR FILTRATION RATE - GFR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLUCOSE  PREDINNER', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLUCOSE 1 HOUR PP', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLUCOSE CHALLENGE TEST', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLUCOSE FASTING', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLUCOSE POST DINNER', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLUCOSE POST LUNCH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLUCOSE PP', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLUCOSE PRE LUNCH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLUCOSE RANDOM(R)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GLUCOSE TOLERANCE TEST', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GROWTH HORMONE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HBA1C/ GLYCOSYLATED HB', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HBV DNA  (VIRAL LODE)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HDL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HSV I & II IGG/IGM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'INTACT PARATHYROID HORMONE(IPTH)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'INTERLEUKIN-6', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'IRON', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'IRON DEFICIENCY PROFILE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'KFT', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LDH - LACTIC DEHYDROGENASE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LDL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LFT', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LFTS', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LH:FSH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LIPASE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LIPID PROFILE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LUPUS ANTI COAGULANT', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'MAGNESIUM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'MICRO ALBUMIN IN URINE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'MUSCLE SPECIFIC KINASE ANTIBODY (MUSK)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'NA+ VALPROIC LEVEL(VALPROIC ACID)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'NA/K (SODIUM/POTASSIUM)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'NEO NATE PACKAGE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'NT PRO - BNP', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PANCA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERICARDIAL FLUID SUGAR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERICARDIAL FLUID-ADA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERICARDIAL FLUID-ALBUMIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERICARDIAL FLUID-LDH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERICARDIAL FLUID-PROTEIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR ADA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR ALBUMIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR CHOLESTEROL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR LDH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR PROTEIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR SUGAR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR TRIGLYCERIDE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PHENYTOIN LEVEL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PHOSPHATE INORGANIC', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PHOSPHORUS', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLASMA METANEPHRINE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR ADA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR ALBUMIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR AMYLASE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR CHOLESTEROL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR LDH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR PROTEIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR SUGAR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR TRIGLYCERIDE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'POST BREAKFAST', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'POTASSIUM (K)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PRACETAMOL LEVEL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PROCALCITONIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PROGESTERONE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PROLACTIN TEST', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PSA FREE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PSA TOTAL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PTH (PARATHYROID HORMONE)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'R-GT (GAMMA  GT)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'RF (QAUNTITATIVE)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'RF TITER', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'RFT', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'RHEUMATIOD FACTOR (RF)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'S PROLACTIN LEVEL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERIUM ERYTHROPOIETIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERIUM OSMOLARITY', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM ACTH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM ALDOSTERONE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM AMYLASE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM ANGIOTENSIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM BICARBONATE LEVEL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM CARBAMAZEPINE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM CERULOPLASMIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM CHOLINESTERASE TEST', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM CORTISOL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM DHEAS', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM DOUBLE MARKER', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM ELECTROLYTE NA,  K (SODIUM, POTASSIUM) ', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM ELECTROPHOROSIS', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM LEPTOSPIRA IGG/IGM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM LITHIUM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM OSMOLARITY', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM PARACETAMOL LEVEL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM PROTEIN ELECTROPHOROSIS', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM TRIPLE MARKER', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SERUM ZINC', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SGOT', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SGPT', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SPOT PCR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SUGAR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID FOR ADA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID-LDH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID-PROTEIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID-SUGAR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID-URIC ACID', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'T3 T4', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'T3 T4 TSH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'T3 TSH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TACROLIMUS', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TB GOLD TEST', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TESTOSTERON FREE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TESTOSTERON TOTAL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TFT (FT3, FT4, TSH)', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'THYROGLOBULIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TIBC', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TOTAL IGE SERUM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TOTAL PROTEIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TOTAL SERUM BILE ACID LEVEL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TRANSGLUTAMINE IGA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TRIGLYCERIEDE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TROPONIN I', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TROPONIN I QUANTITATIVE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TSH', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'UREA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URIC ACID', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE ALBUMIN', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE AMYLASE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE CALCIUM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE CREATININE', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE FOR ACR', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE MAGNESIUM', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE NA/K+', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE OSMOLARITY', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE PHOSPHORUS', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE PROTEIN CREATININE RATIO', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE UREA', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE URIC ACID', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'VALPORIC ACID', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'VALPROIC ACID', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'VITAMIN B12 LEVEL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'VITAMIN D2 (25 OH) LEVEL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'VITAMIN D3 (125 OH) LEVEL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'VITAMIN D3 (25 OH) LEVEL', 'department_id' => '3','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => '24 HRS URINE SP GRAVITY', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BILE SALT AND PIGMENT IN URINE', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CHYLE IN URINE', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'OCCULT BLOOD', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SEMEN ANALYSIS', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'STOOL R/E(ROUTINE)', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE ACETONE\KETONE', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE BENCE JONES PROTEIN', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE DRUG SCREEN FOR MORPHINE', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE DRUG SCREENING FOR AMPHETAMINES', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE DRUG SCREENING FOR CANNABIS', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE DRUG SCREENING FOR COCAINE', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE DRUG SCREENING FOR OPIATES', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE DRUG SCREENING FOR PHENCYCLIDINE', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE PREGNANCY TEST', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE PROTEIN', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE R/E (ROUTINE)', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE SP GRAVITY', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE SUGAR', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE SUGAR/ ALBUMIN', 'department_id' => '4','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID CYTOLOGY', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BONE MARROW ASPIRATION', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CSF CYTOLOGY', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CYTOLOGY FOR MALIGNANT CELLS', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR CYTOLOGY', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FNAC', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PAP SMEAR', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID CYTOLOGY', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID CYTOLOGY', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'REVEIW SLIDES', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SPUTUM CYTOLOGY', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SPUTUM CYTOLOGY (1ST DAY)', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SPUTUM CYTOLOGY (2ND DAY)', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SPUTUM CYTOLOGY (3RD DAY)', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID CYTOLOGY', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID-MALIGNENT CELL', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE CYTOLOGY', 'department_id' => '5','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ABG', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ABSOLUTE EOSINOPHIL COUNT - AEC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ALDEHYDE TEST', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'APTT', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR RBC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR TC/DC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BLOOD GROUPING', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BLOOD TRANSFUSION', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BODY FLUID TC/DC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BONE MARROW ASPIRATION', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BT,CT', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CBC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CSF TC/DC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'DC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ESR', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR RBC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR TC/DC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GIEMSA STAIN', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HB', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HB ELECTRO PHOROSIS', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HCT', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LE CELL (LUPUS ERYTHEMATOUS CELL)', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LUPUS ANTICOAGULENT', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'MALARIA PARASITE (ANTIGEN)', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'MALARIA PARASITE (MP)', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'MICRO FILARIA', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PCV (HCT)', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERICARDIAL FLUID TC/DC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERIPHERAL BLOOD SMEAR (PBS)', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR RBC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR TC DC ', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLATELET COUNT', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR PH', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR RBC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR TC/DC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PT/ INR', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'RBC COUNT', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'RED CELL DISTRIBUTION WIDTH - RDW', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'RETICULOCYTE', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID FOR RBC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID-TC/DC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TC, DC', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TC,DC,PCV,CBC,PLATELETS', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE FOR EOSINOPHIL COUNT', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE RBC MARPHOLOGY', 'department_id' => '6','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BIOPSY  (V.LARGE SPECIMEN)', 'department_id' => '7','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BIOPSY (INTERMEDIATE SPECIMEN)', 'department_id' => '7','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BIOPSY (LARGE SPECIMEN)', 'department_id' => '7','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BIOPSY (SMALL SPECIMEN)', 'department_id' => '7','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BONE MARROW BIOPSY', 'department_id' => '7','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'RENAL BIOPSY', 'department_id' => '7','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SKIN BIOPSY', 'department_id' => '7','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SLIT SKIN SMEAR', 'department_id' => '7','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'AB FOR ECCHINOCOCCAL ANTIGEN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'AFB STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ALLERGY PANEL(IMMUNOBLOT TECHNIQUE)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI DENGUE AB(IGG)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI HAV IGM','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI HBE-IGG','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI HBE-IGM','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI HBS AB TITER','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI HBS ANTIBODY','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI HEV IGM','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI IGG TUBERCULOCIS','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ANTI IGM TUBERCULOCIS','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR AFB','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR GRAM STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BENCE JONES PROTEIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BILE FOR C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BLOOD C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BODY FLUID AFB','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BODY FLUID C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BODY FLUID GRAM STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BONE MARROW ASPIRATION FOR AFB STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BONE MARROW ASPIRATION FOR LD(KALA-AZAR)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BONE MARROW ASPIRATION FOR NON-SALMONELLA','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BONE MARROW C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BRUCELLA ANTIBODY IGG','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BRUCELLA ANTIBODY IGM','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BRUCELLA ANTIGEN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BRUCELLA TOTAL ANTIBODY','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CATHETER TIP C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CHEST TUBE TIPS C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'COVID ANTIBODY (COVID EXPOSURE)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'COVID ANTIBODY (COVID VACCINE )','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CSF AFB','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CSF C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CSF GRAM STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CVP C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'DENGUE IGG/IGM','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'DJ STAIN C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'DRAIN C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ECHINOCOCCUS IGG ANTIBODIES','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ECHINOCOCCUS IGG ANTIBODY ELISA','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ECHINOCOCCUS IGM ANTIBODIES','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ENDOMETRIUM FOR C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ET TUBE C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FAT GLOBULES','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLOOR C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR AFB','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR GRAM STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FOLLEY TIP C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FORMALIN C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FREEZE OT C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FUNGUS CULTURE & SENSIVITY','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FUNGUS STAIN (LPCB)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'GRAM STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'H.PYLORI  ANTIGEN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'H.PYLORI AB ELISA','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'H.PYLORI ANTIBODY  (IGG/IGM)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HANGING DROP','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HAV IGG (RAPID)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HAV IGM ( RAPID )','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HBC ANTIBODY IGM','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HBEAB RAPID','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HBSAG (ELISA)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HBSAG (SPOT)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HCV (ELISA)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HCV (SPOT)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HCV ANTIBODY','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HELICOBACTER PYLORI ANTIBODY','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HEV IGG (RAPID)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HEV IGM ( RAPID )','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HIV (ELISA)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HIV SPOT','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HVS FOR C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'IGG TOXOPLASMA AB','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'IGM TOXOPLASMA AB','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'K-39','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'KOH PREPARATION','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LEPTOSPIRA IGG','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'LEPTOSPIRA IGM','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'MALARIA AG/AB','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'MONITOR C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'MONTOUX','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PATIENT TRALY C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PCN DRAIN C\S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERICARDIAL FLUID-AFB','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERICARDIAL FLUID-C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERICARDIAL FLUID-GRAM STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR AFB','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR GRAM STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR AFB','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR GRAM STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'POC C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PROSTATIC MASSAGE C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PUS C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'REDUCING SUBSTANCE','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'RUBELLA AB IGG','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'RUBELLA AB IGM','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SCRUB TYPHUS IGG/IGM','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SEMEN C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SET UP TRALY C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SPUTUM  AFB 1ST DAY','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SPUTUM  AFB 2ND DAY','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SPUTUM  AFB 3RD DAY','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SPUTUM C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'STOOL C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SUCTION MACHINE C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SUCTION TIP C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SWAB/WOUND/PUS C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID FOR AFB STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SYNOVIAL FLUID FOR GRAIM STAIN','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TB IGA','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TB IGG','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TB IGM','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'THROAT SWAB C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TISSUE CULTURE','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TORCH PROFILE','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TORCH TEST (IGG)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TORCH TEST (IGM)','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TPHA','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URETHERAL SMEAR FOR C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE AFB','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE AFB 1ST DAY','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE AFB 2DAY','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE AFB 3DAY','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'UROBILINOGEN IN URINE','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'VAGINAL C/S','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'VDRL','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'VDRL TITRATION','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'WIDAL','department_id' => '8','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'ASCITIC FLUID FOR PCR','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'BLOOD FOR TB PCR','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'C3 LEVEL','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'C4 LEVEL','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CANCA','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'CERVICAL TISSUE FOR TB PCR','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'COVID-19 AG RAPID TEST','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'FLUID FOR TB PCR','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HBC- IGM  (ANTI HEPATITIS B CORE ANTIGEN)','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HBC-TOTAL IGG (ANTI HEPATITIS B CORE ANTIGEN)','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'HBEAG-(HEPATITIS B ENVELOPE ANTIGEN)','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PCR FOR GENEEXPERT','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PERITONEAL FLUID FOR TB PCR','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'PLEURAL FLUID FOR TB PCR','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'SEMEN FOR AFB PCR','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TB FOR PCR','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'TRIPLE MARKER TEST','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE FOR MICROBACTERIUM PCR','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE FOR TB PCR','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'URINE PCR FOR AFB','department_id' => '9','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')]
        ]);



    }
}
